### ISSUE TITLE
Update to XCGLogger to 3.2

### ISSUE THREAD

**Issue by thebehera** [markuswinkler/XCGLoggerNSLoggerConnector#3]
Can you update the podspec to support XCGLogger 3.2? I want to be able to specifiy the logQueue

**Comment by markuswinkler** [comment]
Thanks for the notice! Updated, it's much more forgiving now on the version number.
I also added a small additional switch.

**Comment by thebehera** [comment]
Sorry any chance we can go to version 3.2? 3.1 is from november!

**Comment by markuswinkler** [comment]
It's set to >=3.1, should work fine with 3.2

**Comment by thebehera** [comment]
Apologies I must of looked at the wrong thing. It's working great! thanks!

**Comment by markuswinkler** [comment]
Sure, np. :)
